---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Update version"
        run: "VERSION='${{ github.ref_name }}' bash -c 'echo ${VERSION//v} > VERSION'"

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: '["VERSION"]'
          message: "Update version"

      - name: "Build mplay package"
        run: nix build .#mplay

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            result/*.zip
